### PR TITLE
Fix: hidden cloudshell dialog scroll bar

### PR DESCRIPTION
**Pull request by zhiyuone**
Signed-off-by: Zhiyu Wang <cloudsky.newbis@gmail.com>

### Description of your changes

Fixes #

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure this PR is ready for review.
- [ ] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer
image

### CODE REVIEW

**Comment by barnettZQG** [comment]
@zhiyuone Why do we need to hide the scroll bar? This will cause content to be truncated.

**Comment by zhiyuone** [comment]
scroll bar affects close button display

**Comment by zhiyuone** [comment]
and hide the scroll bar will cause content to be truncated? I can't reproduce this

**Comment by barnettZQG** [comment]
> and hide the scroll bar will cause content to be truncated? I can't reproduce this

If the content height is more than the window height.

**Comment by zhiyuone** [comment]
oh, this only hidden cloudshell darw scroll bar, cloudshell has its own scroll bar.
image
image

**Comment by barnettZQG** [comment]
@zhiyuone Great!

**Review by barnettZQG — APPROVED** [review]
LGTM

**Pull request merged**
