### PR TITLE
Feat(#536): Graphically display Component and Trait relationships and status

### PR DESCRIPTION
**Pull request by weiy730**
status

Signed-off-by: weiy730 <weiy730@163.com>

### Description of your changes

Feat(https://github.com/kubevela/velaux/issues/536): Graphically display Component and Trait relationships and status

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [x] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### CODE REVIEW

**Comment by barnettZQG** [comment]
@weiy730 Can you provide a screenshot of the new graph?

**Comment by weiy730** [comment]
> @weiy730 Can you provide a screenshot of the new graph?

da.jpg)

**Comment by weiy730** [comment]
> @weiy730 Can you provide a screenshot of the new graph?

**Comment by weiy730** [comment]
> > @weiy730 Can you provide a screenshot of the new graph?
> 
>  

Is there any problem ？

**Review by barnettZQG — APPROVED** [review]
LGTM

**Pull request merged**
