### PR TITLE
Feat: show the kind of the resource

### LINKED ISSUE #549: [Feature] display resource type directly in graph
**Is your feature request related to a problem? Please describe.**

image

It's more convenient!

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

### PR DESCRIPTION
**Pull request by barnettZQG**
Signed-off-by: barnettZQG <barnett.zqg@gmail.com>

### Description of your changes

image

Fixes #549 

I have:

- [x] Read and followed KubeVela's [contribution process](https://github.com/oam-dev/kubevela/blob/master/contribute/create-pull-request.md).
- [ ] [Related Docs](https://github.com/oam-dev/kubevela.io) updated properly. In a new feature or configuration option, an update to the documentation is necessary.
- [x] Run `yarn lint` to ensure this PR is ready for review.
- [x] Added `backport release-x.y` labels to auto-backport this PR if necessary.

### Special notes for your reviewer

/cc @wonderflow

### CODE REVIEW

**Comment by barnettZQG** [comment]
> Pod should be displayed together

What mean?

**Comment by wonderflow** [comment]
image

**Comment by barnettZQG** [comment]
> image

The Pod node is already special enough, so, we don't need to show the Pod kind.

**Comment by wonderflow** [comment]
It's not obvious

**Comment by barnettZQG** [comment]
image

**Review by wonderflow — APPROVED** [review]

**Pull request merged**
